accounts/urls.py
from django.urls import path
from .import views
app_name = 'accounts'

urlpatterns =[
    path('', views.register, name='register'),
    path('login/', views.login, name='login')
]

dashboard/urls.py
from django.urls import path
from .import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.home, name='dashboard'),
    path('add_expenses/', views.add_expenses, name='add_expenses'),
    path('expenses_edit/<int:id>/', views.expense_edit, name='expense_edit'),
    path('delete_expense/<int:id>/', views.delete_expense, name='expense_delete'),
    path('expense_category_summary/', views.expense_category_summary, name='expense_category_summary'),
    path('stats/', views.stats, name='stats')



]

walletwise/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expense/', include('expenses.urls')),
    path('accounts/', include('accounts.urls')),
    path('',include('dashboard.urls')),
    # path('userprofile/',include('userprofile.urls'))
]

# server media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_message.html
{% if messages %}
  <div class="messages">

     {% for message in messages %}  
     <div {% if message.tags %} class=" alert alert-sm alert-{{message.tags}}" {% endif %}>
        {{ message }}
      </div>
          {% endfor %}
      

  </div>

{% endif%}

templates/partials/_sidebar.html
{%load static%}

<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3 sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">

          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:dashboard' %}">

          Expenses
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">
          
        </a>
      </li>
      

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
      <span>Summary</span>
      <a class="link-secondary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle" class="align-text-bottom"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:stats'%}">
          <span data-feather="file-text" class="align-text-bottom"></span>
          Expenses Summary
        </a>
      </li>
      
    </ul>
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
      <span>Settings</span>
      <a class="link-secondary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle" class="align-text-bottom"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:stats'%}">
          <span data-feather="file-text" class="align-text-bottom"></span>
          General Settings
        </a>
      </li>
    </ul>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:stats'%}">
          <span data-feather="file-text" class="align-text-bottom"></span>
          Account Settings
        </a>
      </li>
    </ul>
  </div>
</nav>