accounts/urls.py
from django.urls import path
from .import views
app_name = 'accounts'

urlpatterns =[
    path('', views.register, name='register'),
    path('login/', views.login, name='login')
]

dashboard/urls.py
from django.urls import path
from .import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.home, name='dashboard'),
    path('add_expenses/', views.add_expenses, name='add_expenses'),
    path('expenses_edit/<int:id>/', views.expense_edit, name='expense_edit'),
    path('delete_expense/<int:id>/', views.delete_expense, name='expense_delete'),
    path('expense_category_summary/', views.expense_category_summary, name='expense_category_summary'),
    path('stats/', views.stats, name='stats')



]

walletwise/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expense/', include('expenses.urls')),
    path('accounts/', include('accounts.urls')),
    path('',include('dashboard.urls')),
    # path('userprofile/',include('userprofile.urls'))
]

# server media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
# Create your models here.

class Expense(models.Model):
    amount = models.FloatField()
    date = models.DateField(default= now)
    description = models.TextField(max_length=200)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)
    category = models.CharField(max_length= 200)


    def __str__(self):
        return self.category
       
       # Custom function
    class Meta:
         ordering:['-date']    # type: ignore
    
class Category(models.Model):
    name = models.CharField(max_length= 200)

    class Meta:
         verbose_name_plural= 'Categories'   
    def __str__(self):
            return self.name
    
            
        

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Category, Expense
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import Paginator
import json
from django.http import JsonResponse
import datetime

# Creating an end point
def search_expenses(request):
    if request.method== 'POST':
       

        search_str = json.load(request.body).get('searchText')
         
        expenses =Expense.objects.filter(
            amount__str_with=search_str, owner=request.user) | Expense.objects.filter(
            date__str_with=search_str, owner=request.user)  | Expense.objects.filter(
            category__icontaisn=search_str, owner=request.user) | Expense.objects.filter(
            description__icontains=search_str, owner=request.user) 
        data = expenses.values()

        return JsonResponse(list(data), safe=False)




# Create your views here.
@login_required(login_url='/accounts/login')
def home(request):
    categories =Category.objects.all()
    expenses=Expense.objects.filter(owner=request.user)
    paginator=Paginator(expenses, 5) # show 5 objects per page
    page_number=request.GET.get('page')
    page_obj=Paginator.get_page(paginator, page_number)
    user= request.user
    context={
            'expenses': expenses,
            'page_obj': page_obj,
            'username': user.username
        }
    return render(request, '_dashboard/index.html', context )


#Updating the records  
@login_required(login_url='/accounts/login')
def add_expenses(request):
    expenses=Expense.objects.filter(owner=request.user)
    categories = Category.objects.all()
    context= { 
        'expenses' : expenses,
        'categories': categories,
        'values': request.POST
        
    } 
    if request.method== 'GET':
        return render(request, '_dashboard/add_expenses.html', context)

    # To check if  fields are empty and display a message if empty
    if request.method== 'POST':
        amount = request.POST['amount']

        if not amount:
            messages.error(request, 'Amount is required')
            return render(request, '_dashboard/add_expenses.html', context)
    

        
        description = request.POST['description']
        date = request.POST['date']
        category = request.POST['category']

        if not description:
            messages.error(request, 'Description is required')
            return render(request, '_dashboard/add_expenses.html', context)
        if not date:
            messages.error(request, 'Date is required')
            return render(request, '_dashboard/add_expenses.html', context)
        
        # Pushing the records in the database
        Expense.objects.create(owner=request.user,amount=amount, date=date, category=category, description=description)

        messages.success(request, 'Expense saved successfully')

        return redirect( 'dashboard:dashboard')
     

@login_required(login_url='/accounts/login')    
def expense_edit(request, id):
    expense =Expense.objects.get(pk=id)
    categories= Category.objects.all()
    context = {
        'expense': expense,
        'values': expense,
        'categories': categories
    }
    if request.method == 'GET':
        return render(request, '_dashboard/expense_edit.html', context )
    else:
     if request.method == 'POST':
        amount = request.POST['amount']

        if not amount:
            messages.error(request, 'Amount is required')
            return render(request, '_dashboard/add_expenses.html', context)
    

        
        description = request.POST['description']
        date = request.POST['date']
        category = request.POST['category']

        if not description:
            messages.error(request, 'Description is required')
            return render(request, '_dashboard/add_expenses.html', context)
        if not date:
            messages.error(request, 'Date is required')
            return render(request, '_dashboard/add_expenses.html', context)
        
        # Pushing the records in the database
        Expense.objects.create(owner=request.user,amount=amount, date=date, category=category, description=description)
        expense.owner=request.user
        expense.amount=amount 
        expense.date=date 
        expense.category=category
        expense.description=description

        expense.save()
        messages.success(request, 'Expense updated successfully')

        return redirect( 'dashboard:dashboard')
@login_required(login_url='/accounts/login')
def delete_expense(request, id):
    expense=Expense.objects.get(pk=id)
    expense.delete()
    messages.success(request, 'Expense removed')
    return redirect( 'dashboard:dashboard')

# endpoint for charts
@login_required(login_url='/accounts/login')
def expense_category_summary(request):
    todays_date= datetime.date.today() # Gets today's date
    six_months_ago= todays_date-datetime.timedelta(days=360) # Represents a duration of 360 days
    expenses=Expense.objects.filter(owner=request.user,date__gte=six_months_ago, date__lte=todays_date)
    # creating a dictionary to store each category as a key and its total expenses as the value
    finalrep= {}
    
    # Function to return expenses based on category
    def get_category(expense):
        return expense.category
    category_list= list(set(map(get_category, expenses)))
    # Function to return the calculted expenses of each category
    def get_expense_category_amount(category):
        amount= 0
        filter_by_category = expenses.filter(category= category)
        # To sum up the amounts of all filtered expenses
        for item in filter_by_category:
            amount += item.amount 
        return amount
    
    for i in expenses:
        for j in category_list:
            finalrep[j]=get_expense_category_amount(j)

    return JsonResponse({'expense_category_date': finalrep},safe=False)          

@login_required(login_url='/accounts/login')
def stats(request):
    return render(request, '_dashboard/stats.html')

templates/_dashboard/add_expenses.html
{% extends '_base.html'%}
{% load static %}

{% block title%} Add_Expenses {% endblock %}

{% block content %}
<div class="container mt-2">
   
         <nav aria-label="breadcrumb">
             <ol class="breadcrumb">
             <li class="breadcrumb-item">
                 <a href="{% url 'dashboard:dashboard'%}">Expenses</a></li>
             <li class="breadcrumb-item active" aria-current="page">Add expenses</li>
             </ol>
         </nav>
     
<div class="card">
 <div class="card-body">
    <form action="{% url 'dashboard:add_expenses'%}" method="post">
     
      {% include 'partials/_message.html'%}
      {% csrf_token %}
     
        <div class="form-group">
            <label for="">Amount</label>
            <input type="number" class="form-control form-control-sm" name="amount" value="{{values.amount}}">
        </div>
        <div class="form-group">
            <label for="">Category</label>
            <select class="form-control" name="category" >
                {% for category in categories %} 
                <option name="category" value="{{category.name}}">{{category.name}} </option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="">Description</label>
            <input type="text" class="form-control form-control-sm" name="description" value="{{values.description}}">
        </div>

        <div class="form-group">
            <label for="">Date of Expense</label>
            <input type="date" class="form-control form-control-sm " name="date">
        </div>
        <input type="submit" value="submit" class="btn btn-primary btn-primary-sm mt-2">
  </form>
 </div>
</div>
</div>

{% endblock %}

templates/_dashboard/delete_expenses.html
extends '_base.html'%}
{% load static %}

{% block title%} Add_Expenses {% endblock %}

{% block content %}
<div class="container mt-2">
   
         <nav aria-label="breadcrumb">
             <ol class="breadcrumb">
             <li class="breadcrumb-item">
                 <a href="{% url 'dashboard:dashboard'%}">Expenses</a></li>
             <li class="breadcrumb-item active" aria-current="page">Add expenses</li>
             </ol>
         </nav>
     
<div class="card">
 <div class="card-body">
    <form action="{% url 'dashboard:add_expenses'%}" method="post">
     
      {% include 'partials/_message.html'%}
      {% csrf_token %}
     
        <div class="form-group">
            <label for="">Amount</label>
            <input type="number" class="form-control form-control-sm" name="amount" value="{{values.amount}}">
        </div>
        <div class="form-group">
            <label for="">Category</label>
            <select class="form-control" name="category" >
                {% for category in categories %} 
                <option name="category" value="{{category.name}}">{{category.name}} </option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="">Description</label>
            <input type="text" class="form-control form-control-sm" name="description" value="{{values.description}}">
        </div>

        <div class="form-group">
            <label for="">Date of Expense</label>
            <input type="date" class="form-control form-control-sm " name="date">
        </div>
        <input type="submit" value="submit" class="btn btn-primary btn-primary-sm mt-2">
  </form>
 </div>
</div>

{% endblock %}

templates/_dashboard/expense_edit.html
{% extends '_base.html'%}
{% load static %}

{% block title%} Add_Expenses {% endblock %}

{% block content %}
<div class="container mt-2">
  <div class="row">
    <div class="col-md-10">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard:dashboard'%}">Expenses</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit expenses</li>
            </ol>
        </nav>
    </div>
    <div class="col-md-2">
        
    </div>
  </div> 
     
<div class="card">
 <div class="card-body">
    <form action="{% url 'dashboard:expense_edit' expense.id %}" method="post">
     
      {% include 'partials/_message.html'%}
      {% csrf_token %}
     
        <div class="form-group">
            <label for="">Amount</label>
            <input type="number" class="form-control form-control-sm" name="amount" value="{{values.amount}}">
        </div>
        <div class="form-group">
            <label for="">Category</label>
            <select class="form-control" name="category" >
                <option selected name="category" value="{{values.category}}">{{values.category}} </option>
                {% for category in categories %} 
                <option name="category" value="{{category.name}}">{{category.name}} </option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="">Description</label>
            <input type="text" class="form-control form-control-sm" name="description" value="{{values.description}}">
        </div>

        <div class="form-group">
            <label for="">Date of Expense</label>
            <input type="date" class="form-control form-control-sm " name="date">
        </div>
        <input type="submit" value="Save" class="btn btn-primary btn-primary-sm mt-2">
  </form>
 </div>
</div>

{% endblock %}

templates/_dashboard/index.html
{% extends '_base.html'%}
{% load static%}

{% block title%} My Expenses {% endblock%}


{% block content%}
 <div class="container mt-4">
    
   <div class="row ">
    <div class="col-md-10 ">
        <nav aria-label="breadcrumb bg-light">
            <ol class="breadcrumb">
            <li class="breadcrumb-item ">
                <a href="">Expenses</a></li>
            <li class="breadcrumb-item active" aria-current="page">My expenses</li>
            </ol>
        </nav>
    </div>
    <div class="col-md-2">
        <a href="{% url 'dashboard:add_expenses'%}" class="btn btn-primary ">AddExpense</a>
    </div>
   </div>

   <div class="container mt-2">
    {% include 'partials/_message.html'%}
    {% if expenses.count %}
    <div> Welcome back, {{ username }}!</div>
    <div class="card">
      <div class="card-body"></div>  
    <div class="row col-md-8"></div>
    <div class="row col-md-4">
        <div class="form-group ">
            <input type="text" class="form-control" id="searchField" placeholder="Search" >
        </div>
    </div>
    <table class="table table-stripped table-hover ">
        <thead>
            <tr>
               <th>Amount</th>
               <th>Category</th>
               <th>Description</th>
               <th>Date</th>
               <th></th>

            </tr>
        </thead>
        <tbody>


            {% for expense in page_obj %}
            <tr>
            <td>{{expense.amount}} </td>
            <td>{{expense.category}}</td>
            <td>{{expense.description}}</td>
            <td>{{expense.date}}</td>
            <td><a href="{% url 'dashboard:expense_edit' expense.id %}" class="btn btn-primary btn-sm">Edit</a>
            </td>
            <td><a href="{% url 'dashboard:expense_delete' expense.id%}" class="btn btn-danger btn-sm">Delete</a></td>
            
        </tr>
            {% endfor %}
        </tbody>
    </table>

     <div class="paginator-info">
       Showing Page{{page_obj.number}} of {{ page_obj.paginator.num_pages }} 

     </div>
    <ul class="pagination align-right float-right ar-auto">
       {% if page_obj.has_previous %} 
       <li {% if page_obj.number == 1 %} class="page_item active" {%endif%}> <a href="?page=1" class="page_link">&laquo; 1 </a> </li>
       <li class="page_item"> <a href="?page={{ page_obj.previous_page_umber }}" class="page_link">Previous</a> </li>
       {%endif%}
       
       {% if page_obj.has_next %}
       <li class="page_item" > <a class="page_link" href="?page={{ page_obj.next_page_number }}">Next</a> </li>
       <li class="page_item"> <a class="page_link" href="?page={{ page_obj.paginator.num_pages }}"> {{ page_obj.paginator.num_pages }}&raquo; </a> </li>
       {%endif%}
       


    </ul>
    

   {% endif %}
   </div>
   </div>
 </div>

 <script src="{% static 'assets/js/searchExpenses.js'%}">
      

 </script>
 
{% endblock %}

templates/_dashboard/stats.html
{% extends '_base.html'%}
{% load static%}

{% block title%} Stats {% endblock%}


{% block content%}
 <div class="container mt-4">
    
   <div class="row ">
    <div class="col-md-10 ">
        <nav aria-label="breadcrumb bg-light">
            <ol class="breadcrumb">
            <li class="breadcrumb-item ">
                <a href="">Expenses Summary</a></li>
            <li class="breadcrumb-item active" aria-current="page">Summary</li>
            </ol>
        </nav>
    </div>
    <div class="col-md-2">
        <a href="{% url 'dashboard:dashboard'%}" class="btn btn-primary ">Back</a>

    </div>
    <div>
        <canvas id="expenseChart" width="400" height="400"></canvas>



        
      </div>
      
     
       
   </div>
   
</div>

 <!-- <script src="{% static 'assets/js/stats.js'%}"> -->
      

 </script>    
 
{% endblock %}

templates/_dashboard/update_expenses.html
{% extends '_base.html'%}
{% load static %}

{% block title%} Update_expense {% endblock %}

{% block content %}
<div class="container mt-4">
   
         <nav aria-label="breadcrum">
             <ol class="breadcrumb">
             <li class="breadcrumb-item background-dark">
                 <a href="{% url 'dashboard:dashboard'%}">Expenses</a></li>
             <li class="breadcrumb-item active" aria-current="page">Edit expense</li>
             </ol>
         </nav>
     

<div class="card-body">
  <form action="{% url 'dashboard:add_expenses'%}" method="post"></form>
     {% csrf_token %}
     {% include 'partials/_message.html'%}
        <div class="form-group">
            <label for="">Amount</label>
            <input type="number" class="form-control form-control-sm" name="amount" value="{{values.amount}}">
        </div>
        <div class="form-group">
            <label for="">Category</label>
            <select class="form-control" name="category" >
                {% for category in categories %} 
                <option name="category" value="{{category.name}}">{{category.name}} </option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="">Description</label>
            <textarea type="text" class="form-control form-control-sm" name="description" value="{{values.description}}"> </textarea>
        </div>

        <div class="form-group">
            <label for="">Date of Expense</label>
            <input type="date" class="form-control form-control-sm " name="date" value="{{values.date}}">
        </div>
        <input type="submit" value="Update" class="btn btn-primary btn-primary-sm mt-2">
  </form>
</div>
</div>

{% endblock %}