accounts/urls.py
from django.urls import path
from .import views
app_name = 'accounts'

urlpatterns =[
    path('', views.register, name='register'),
    path('login/', views.login, name='login')
]

walletwise/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expense/', include('expenses.urls')),
    path('accounts/', include('accounts.urls')),
    path('',include('dashboard.urls')),
    # path('userprofile/',include('userprofile.urls'))
]

# server media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/authentication/__base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {%block title%}{% endblock %} </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/auth.css'%}">
    
</head>
<body>

    <div class="card">
        <div class="card-body">
           <main>
            {% block content%}

            {% endblock%}
           </main>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/authentication/login.html
{% extends 'authentication/__base.html'%}
{% load static%}
{% block title %} Login {% endblock %}

{% block content%}



<form action="{% url 'accounts:login' %}" method="post">
    {% include 'partials/_message.html'%}
    {% csrf_token%}
    <div class="form-group">
        <label for="username" class="cols-sm-2 control-label">Username</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter your Username" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="cols-sm-2 control-label">Password</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter your Password" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Login</button>
    </div>
    <div class="login-register">
        <a href="{% url 'accounts:register' %}">Register</a>
    </div>
</form>
       

{% endblock %}

templates/authentication/register.html
{% extends 'authentication/__base.html'%}
{% load static%}
{% block title %} Register {% endblock %}

{% block content%}

<form action="{% url 'accounts:register' %}" method="post">
    {% include 'partials/_message.html'%}
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="cols-sm-2 control-label">Your Name</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter your Name"  value="{{values.name}}"/>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="username" class="cols-sm-2 control-label">Username</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter your Username" value="{{values.username}}"/>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="cols-sm-2 control-label">Your Email</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="email" id="email" placeholder="Enter your Email" value="{{values.email}}"/>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label for="password" class="cols-sm-2 control-label">Password</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter your Password" value="{{values.password}}" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
        <div class="cols-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                <input type="password" class="form-control" name="confirm" id="confirm" placeholder="Confirm your Password" value="{{values.confirm}}"/>
            </div>
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register</button>
    </div>
    <div class="login-register">
        <a href="{% url 'accounts:login'%}">Login</a>
    </div>
</form>


{% endblock %}